#!/bin/bash

# Gather tweets
if [ ! -e "gather-tweets" ]; then
    # Check if curl is installed
    if command -v curl &> /dev/null; then
        curl -s -O https://raw.githubusercontent.com/PsySecGroup/gather-tweets/main/gather-tweets
        chmod u+x gather-tweets
    # Check if wget is installed
    elif command -v wget &> /dev/null; then
        wget -q https://raw.githubusercontent.com/PsySecGroup/gather-tweets/main/gather-tweets
        chmod u+x gather-tweets
    else
        echo "Neither curl nor wget found. Please install either of them."
    fi
fi

# A second argument in the CLI will prevent a tweet gather
if [ ! $2 ]; then
  ./gather-tweets $1
  mv $1.csv targets/
fi

# Get python command
if command -v python &> /dev/null; then
    pythonCommand='python'
elif command -v python3 &> /dev/null; then
    pythonCommand='python3'
elif command -v python27 &> /dev/null; then
    pythonCommand='python27'
fi

# Bootleg import system
eval "$pythonCommand" <<EOF
import re
file_location = "template.html"
with open(file_location, "r") as file:
  contents = file.readlines()
pattern = r'^[ ]+import \'\.\/([^\']+)\''
for i in range(len(contents)):
  matches = re.findall(pattern, contents[i])
  if len(matches) > 0:
    with open(matches[0], "r") as new_file:
      contents[i] = new_file.read()
  else:
    contents[i] = contents[i]
with open("targets/$1.html", "w") as file:
  for line in contents:
    file.write(line)
EOF

# Defeating jitsi seeking attempts
random_id=$(shuf -i 10000000-99999999 -n 1)

# Add target info
sed -i "s|{{target}}|$1|g" targets/$1.html

# Hook in Jitsi embed
sed -i "s|roomName: '{{jitsi}}',|roomName: 'gloat-hunting-$1-$random_id',|g" targets/$1.html
sed -i "s|const seed = 'random_id'|const seed = $random_id|g" targets/$1.html

# Convert everything to an acceptable format
awk -F'\t' 'NR>1 { gsub(/[-:]/, " ", $3); t = mktime($3 " 00"); tweet = $11; sub("\t.*", "", tweet); print strftime("%Y-%m-%dT%H:%M:%SZ\t", t), tweet }' targets/$1.csv > targets/$1.txt

# Strips all mentions, RTs, HTML entities, and starting spaces from the output text
sed -i -E 's/@[^[:space:]]*//g; s/`//g; s/\t[[:space:]]*/\t/g; s/\t.?RT[[:space:]][[:space:]]*/\t/g; s/&[^;]{1,6};/&/g' targets/$1.txt

# Geneates the GUI
sed -i -e "/{{replaceMe}}/r targets/$1.txt" -e '/{{replaceMe}}/d' targets/$1.html

# Open the GUI
if command -v xdg-open &> /dev/null; then
    xdg-open targets/$1.html
elif command -v open &> /dev/null; then 
    open targets/$1.html
elif command -v start &> /dev/null; then
    start targets/$1.html
fi

# Uploads the HTML to Keep.sh and gives you a link to share with fellow researchers
#echo "Share this link with fellow researchers so they can help! (This link will self-terminate in 24 hours)"
#LINK=$(curl -s --upload-file targets/$1.html https://free.keep.sh)
